[package]
name = "basic-setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crunch = { workspace = true,default-features = false, features = ["in-memory"] }

tracing.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
prost.workspace = true
