[package]
name = "crunch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tokio.workspace = true
thiserror.workspace = true
async-trait.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true